name: Tests for pull requests

on:
  pull_request:
    branches: [main]

jobs:
  build-tests:
    name: Run Build Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build edge-app container image
        run: ./try-margo/plugfest202607/apps/edge-app/build_container_image.sh

      - name: Run tests
        run: ./try-margo/plugfest202607/apps/edge-app/run_tests.sh

  push-images:
    name: Push Container Images
    runs-on: ubuntu-latest
    needs: build-tests
    permissions:
      # イメージをプッシュする権限をGITHUB_TOKENに付与する
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      REGISTRY_TOKEN_NAME: ${{ github.actor }}
      REGISTRY_TOKEN_PASSWD: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_TAG: develop
      MULTI_ARCH_BUILD: true

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build edge-app container image
        run: ./try-margo/plugfest202607/apps/edge-app/build_container_image.sh

      - name: Push container images
        run: ./try-margo/plugfest202607/apps/push_container_images.sh

  k3s-tests:
    name: Test helm-chart on k3s
    runs-on: ubuntu-latest
    needs: push-images

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run helm chart test
        run: ./try-margo/plugfest202607/apps/edge-app/run_helm_chart_tests.sh
